name: Build

on: [push, pull_request]

jobs:
  build-project:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Install Dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: >
          sudo apt install -y python3 python3-yaml
          sudo apt install -y pkg-config libwayland-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxkbcommon-dev

      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0