name: Build

on:
  push:

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt install -y python3 python3-yaml
      - run: sudo apt install -y pkg-config libwayland-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxkbcommon-dev

      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0